/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MatchRouteImport } from './routes/_match'
import { Route as EventMatchRouteImport } from './routes/_eventMatch'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MatchMatchIdRouteImport } from './routes/match.$matchId'
import { Route as MatchSummaryRouteImport } from './routes/_match.summary'
import { Route as MatchSetupRouteImport } from './routes/_match.setup'
import { Route as MatchGameRouteImport } from './routes/_match.game'
import { Route as MatchMatchIdSummaryRouteImport } from './routes/match.$matchId.summary'
import { Route as MatchMatchIdSetupRouteImport } from './routes/match.$matchId.setup'
import { Route as MatchMatchIdGameGameIdRouteImport } from './routes/match.$matchId.game.$gameId'

const MatchRoute = MatchRouteImport.update({
  id: '/_match',
  getParentRoute: () => rootRouteImport,
} as any)
const EventMatchRoute = EventMatchRouteImport.update({
  id: '/_eventMatch',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchMatchIdRoute = MatchMatchIdRouteImport.update({
  id: '/match/$matchId',
  path: '/match/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchSummaryRoute = MatchSummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => MatchRoute,
} as any)
const MatchSetupRoute = MatchSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => MatchRoute,
} as any)
const MatchGameRoute = MatchGameRouteImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => MatchRoute,
} as any)
const MatchMatchIdSummaryRoute = MatchMatchIdSummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => MatchMatchIdRoute,
} as any)
const MatchMatchIdSetupRoute = MatchMatchIdSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => MatchMatchIdRoute,
} as any)
const MatchMatchIdGameGameIdRoute = MatchMatchIdGameGameIdRouteImport.update({
  id: '/game/$gameId',
  path: '/game/$gameId',
  getParentRoute: () => MatchMatchIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/game': typeof MatchGameRoute
  '/setup': typeof MatchSetupRoute
  '/summary': typeof MatchSummaryRoute
  '/match/$matchId': typeof MatchMatchIdRouteWithChildren
  '/match/$matchId/setup': typeof MatchMatchIdSetupRoute
  '/match/$matchId/summary': typeof MatchMatchIdSummaryRoute
  '/match/$matchId/game/$gameId': typeof MatchMatchIdGameGameIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/game': typeof MatchGameRoute
  '/setup': typeof MatchSetupRoute
  '/summary': typeof MatchSummaryRoute
  '/match/$matchId': typeof MatchMatchIdRouteWithChildren
  '/match/$matchId/setup': typeof MatchMatchIdSetupRoute
  '/match/$matchId/summary': typeof MatchMatchIdSummaryRoute
  '/match/$matchId/game/$gameId': typeof MatchMatchIdGameGameIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_eventMatch': typeof EventMatchRoute
  '/_match': typeof MatchRouteWithChildren
  '/_match/game': typeof MatchGameRoute
  '/_match/setup': typeof MatchSetupRoute
  '/_match/summary': typeof MatchSummaryRoute
  '/match/$matchId': typeof MatchMatchIdRouteWithChildren
  '/match/$matchId/setup': typeof MatchMatchIdSetupRoute
  '/match/$matchId/summary': typeof MatchMatchIdSummaryRoute
  '/match/$matchId/game/$gameId': typeof MatchMatchIdGameGameIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/game'
    | '/setup'
    | '/summary'
    | '/match/$matchId'
    | '/match/$matchId/setup'
    | '/match/$matchId/summary'
    | '/match/$matchId/game/$gameId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/game'
    | '/setup'
    | '/summary'
    | '/match/$matchId'
    | '/match/$matchId/setup'
    | '/match/$matchId/summary'
    | '/match/$matchId/game/$gameId'
  id:
    | '__root__'
    | '/'
    | '/_eventMatch'
    | '/_match'
    | '/_match/game'
    | '/_match/setup'
    | '/_match/summary'
    | '/match/$matchId'
    | '/match/$matchId/setup'
    | '/match/$matchId/summary'
    | '/match/$matchId/game/$gameId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EventMatchRoute: typeof EventMatchRoute
  MatchRoute: typeof MatchRouteWithChildren
  MatchMatchIdRoute: typeof MatchMatchIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_match': {
      id: '/_match'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_eventMatch': {
      id: '/_eventMatch'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof EventMatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match/$matchId': {
      id: '/match/$matchId'
      path: '/match/$matchId'
      fullPath: '/match/$matchId'
      preLoaderRoute: typeof MatchMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_match/summary': {
      id: '/_match/summary'
      path: '/summary'
      fullPath: '/summary'
      preLoaderRoute: typeof MatchSummaryRouteImport
      parentRoute: typeof MatchRoute
    }
    '/_match/setup': {
      id: '/_match/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof MatchSetupRouteImport
      parentRoute: typeof MatchRoute
    }
    '/_match/game': {
      id: '/_match/game'
      path: '/game'
      fullPath: '/game'
      preLoaderRoute: typeof MatchGameRouteImport
      parentRoute: typeof MatchRoute
    }
    '/match/$matchId/summary': {
      id: '/match/$matchId/summary'
      path: '/summary'
      fullPath: '/match/$matchId/summary'
      preLoaderRoute: typeof MatchMatchIdSummaryRouteImport
      parentRoute: typeof MatchMatchIdRoute
    }
    '/match/$matchId/setup': {
      id: '/match/$matchId/setup'
      path: '/setup'
      fullPath: '/match/$matchId/setup'
      preLoaderRoute: typeof MatchMatchIdSetupRouteImport
      parentRoute: typeof MatchMatchIdRoute
    }
    '/match/$matchId/game/$gameId': {
      id: '/match/$matchId/game/$gameId'
      path: '/game/$gameId'
      fullPath: '/match/$matchId/game/$gameId'
      preLoaderRoute: typeof MatchMatchIdGameGameIdRouteImport
      parentRoute: typeof MatchMatchIdRoute
    }
  }
}

interface MatchRouteChildren {
  MatchGameRoute: typeof MatchGameRoute
  MatchSetupRoute: typeof MatchSetupRoute
  MatchSummaryRoute: typeof MatchSummaryRoute
}

const MatchRouteChildren: MatchRouteChildren = {
  MatchGameRoute: MatchGameRoute,
  MatchSetupRoute: MatchSetupRoute,
  MatchSummaryRoute: MatchSummaryRoute,
}

const MatchRouteWithChildren = MatchRoute._addFileChildren(MatchRouteChildren)

interface MatchMatchIdRouteChildren {
  MatchMatchIdSetupRoute: typeof MatchMatchIdSetupRoute
  MatchMatchIdSummaryRoute: typeof MatchMatchIdSummaryRoute
  MatchMatchIdGameGameIdRoute: typeof MatchMatchIdGameGameIdRoute
}

const MatchMatchIdRouteChildren: MatchMatchIdRouteChildren = {
  MatchMatchIdSetupRoute: MatchMatchIdSetupRoute,
  MatchMatchIdSummaryRoute: MatchMatchIdSummaryRoute,
  MatchMatchIdGameGameIdRoute: MatchMatchIdGameGameIdRoute,
}

const MatchMatchIdRouteWithChildren = MatchMatchIdRoute._addFileChildren(
  MatchMatchIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EventMatchRoute: EventMatchRoute,
  MatchRoute: MatchRouteWithChildren,
  MatchMatchIdRoute: MatchMatchIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
